// e2e framework — types shared across runner / harness / scenarios.

export interface ToolCall {
  toolCallId: string
  toolName: string
  input: Record<string, unknown>
  /** Result text if a paired tool-result was found in the same session. */
  resultText?: string
  /** Whether the tool result was marked as an error by the provider/tool. */
  isError?: boolean
}

export interface RunResult {
  /** Final concatenated assistant text from all assistant messages in this run. */
  assistantText: string
  /** All tool calls, in invocation order, with paired results merged in when present. */
  toolCalls: ToolCall[]
  /** Raw stdout from `xc -p`. May still be useful for debugging. */
  stdout: string
  /** Raw stderr. */
  stderr: string
  /** Process exit code. */
  exitCode: number
  /** Wall-clock duration in ms. */
  durationMs: number
  /** Absolute path to the session jsonl file generated by this run. Empty if none. */
  sessionJsonlPath: string
  /** Tokens reported by the latest usage entry, if any. */
  tokenUsage?: { input: number; output: number; cacheRead: number; cacheWrite: number }
}

export interface RunCliOptions {
  /** Extra CLI args (e.g. `['--trust', '--max-turns', '20']`). */
  args?: string[]
  /** Override seconds-budget. Default 120s. */
  timeoutMs?: number
  /** Extra env to merge on top of base env (which already sets X_CODE_HOME / model). */
  env?: Record<string, string>
  /** Working directory; defaults to the scenario tmpDir. */
  cwd?: string
}

export interface ScenarioContext {
  /** Absolute path to this scenario's temp directory. CWD for the CLI run. */
  tmpDir: string
  /** Selected model id, already mapped through MODEL_ALIASES. */
  modelId: string
  /** Path to packages/cli/dist/cli.js (resolved by the runner once). */
  cliBin: string
  /** Available env (filtered to *_API_KEY plus a few). */
  env: Record<string, string>

  // ── File helpers (paths are relative to tmpDir unless absolute) ──
  writeFile(relPath: string, content: string): Promise<void>
  readFile(relPath: string): Promise<string>
  fileExists(relPath: string): Promise<boolean>
  mkdir(relPath: string): Promise<void>

  // ── CLI runner ──
  runCli(prompt: string, options?: RunCliOptions): Promise<RunResult>

  // ── Assertion helpers (throw ScenarioAssertionError on fail) ──
  expect: ScenarioExpect
}

export interface ScenarioExpect {
  /** Assert a tool was called at least once. inputMatcher accepts a partial object
   *  with values that are either equal, a RegExp, or a predicate. */
  toolCalled(
    result: RunResult,
    toolName: string,
    inputMatcher?: Record<string, unknown | RegExp | ((v: unknown) => boolean)>,
  ): ToolCall
  toolNotCalled(result: RunResult, toolName: string): void
  /** Assert the concatenated assistant text matches a substring or regex. */
  assistantMentions(result: RunResult, needle: string | RegExp): void
  /** Assert exit code. */
  exitCode(result: RunResult, code: number): void
  /** Assert a file exists at tmpDir-relative path. */
  fileExists(relPath: string): Promise<void>
  /** Assert a file's content matches substring or regex. */
  fileContent(relPath: string, matcher: string | RegExp): Promise<void>
  /** Assert no tool call ended up with isError. */
  noToolErrors(result: RunResult): void
  /** Custom assertion: throw with given message if condition is falsy. */
  truthy(condition: unknown, message: string): void
}

export interface Scenario {
  /** Stable id used for state persistence and CLI filtering. Use `01-` prefix
   *  so files sort naturally. */
  id: string
  /** Human-readable name shown in progress output. */
  name: string
  /** If set, scenario is skipped when the env predicate returns false.
   *  Use this for scenarios that need optional keys (e.g. TAVILY_API_KEY). */
  requires?: (env: Record<string, string>) => boolean
  /** Skip reason shown when `requires` returns false. */
  requiresReason?: string
  /** The actual test body. Should throw on failure. */
  run(ctx: ScenarioContext): Promise<void>
}

export interface ScenarioResult {
  id: string
  name: string
  status: 'passed' | 'failed' | 'skipped'
  /** Wall-clock duration in seconds. */
  durationSec: number
  /** Short human-readable error message; only set when status === 'failed'. */
  error?: string
  /** Path to the session jsonl from the latest CLI run within this scenario. */
  lastSessionJsonl?: string
  /** Path to the scenario's tmpDir (kept on failure, deleted on pass). */
  tmpDir?: string
  /** Skip reason (if status === 'skipped'). */
  skipReason?: string
}

export interface RunState {
  /** Last selected model id. */
  model: string
  /** ISO timestamp of last run start. */
  startedAt: string
  /** Per-scenario results, keyed by scenario id. */
  results: Record<string, ScenarioResult>
}

export class ScenarioAssertionError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'ScenarioAssertionError'
  }
}
