export const MAX_AUDIO_SOURCE_BYTES = 25 * 1024 * 1024
export const MAX_AUDIO_DURATION_SECONDS = 20 * 60
export const WHISPER_PCM_SAMPLE_RATE = 16_000
export const MAX_AUDIO_PCM_SAMPLES = MAX_AUDIO_DURATION_SECONDS * WHISPER_PCM_SAMPLE_RATE
export const MAX_AUDIO_PCM_INPUT_BYTES = MAX_AUDIO_PCM_SAMPLES * Int16Array.BYTES_PER_ELEMENT
export const MAX_AUDIO_DECODED_PCM_BYTES = MAX_AUDIO_PCM_SAMPLES * Float32Array.BYTES_PER_ELEMENT
